name: PostTutorialMixApp
description: A sample command-line application
dev_dependencies:
  browser: any
  dartabase_model: 0.6.3
  json_object: '>=1.0.18+2 <2.0.0'
  params: 0.0.2
  polymer: ">=0.12.0 <0.13.0"
transformers:
- polymer:
    entry_points: 
    - web/index.html
    - web/item/index.html
    - web/item/create.html
    - web/item/edit.html
    - web/item/view.html
environment:
  sdk: '>=0.8.10+6 <2.0.0'
    