name: PostTutorialMixApp
description: A sample command-line application
dev_dependencies:
  browser: any
  dartabase_model: 0.6.3
  json_object: '>=1.0.18+2 <2.0.0'
  params: 0.0.2
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
